In [16]:
pip install imblearn

Note: you may need to restart the kernel to use updated packages.


In [1]:
import pandas as pd
import os
import numpy as np  
import matplotlib.pyplot as plt  
import seaborn as sns
%matplotlib inline

In [2]:
df = pd.read_csv('Data\\Data.csv',index_col = 0)

D:\Softwares\Anaconda\lib\site-packages\numpy\lib\arraysetops.py:569: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


In [3]:
df.isnull().sum()

Quarter            0
Month              0
DayofMonth         0
FlightDate         0
OriginAirportID    0
DestAirportID      0
Dest               0
CRSDepTime         0
DepTime            0
DepDelayMinutes    0
DepDel15           0
CRSArrTime         0
ArrTime            0
ArrDelayMinutes    0
ArrDel15           0
Unnamed: 0         0
windspeedKmph      0
visibility         0
weatherCode        0
precipMM           0
WindGustKmph       0
pressure           0
cloudcover         0
winddirDegree      0
humidity           0
DewPointF          0
tempF              0
time               0
WindChillF         0
date               0
place              0
dtype: int64

In [4]:
y = df['ArrDel15']
X = df.drop(['ArrDel15','FlightDate','date','place','ArrDelayMinutes','ArrTime','Unnamed: 0'],axis = 1)

In [5]:
from sklearn.model_selection import train_test_split  
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 101) 

In [8]:
y_train.value_counts()

1.0    310080
0.0    310080
Name: ArrDel15, dtype: int64

In [7]:
from imblearn.under_sampling import RandomUnderSampler
rus = RandomUnderSampler(random_state = 42)
X_train, y_train = rus.fit_resample(X_train,y_train)

### Logistic Regression

In [9]:
from sklearn.linear_model import LogisticRegression
logreg = LogisticRegression()
logreg.fit(X_train,y_train)

D:\Softwares\Anaconda\lib\site-packages\sklearn\linear_model\_logistic.py:764: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression()

In [10]:
logy_pred = logreg.predict(X_test)

In [11]:
#Performance Metrics

from sklearn.metrics import accuracy_score, classification_report
from sklearn import metrics

print('Accuracy Score: ',accuracy_score(y_test, logy_pred))
cm = metrics.confusion_matrix(y_test, logy_pred)
print('Confusion Matrix\n',cm)
target_names=["Class 0","Class 1"]
print('Classification Report\n',classification_report(y_test, logy_pred,target_names=target_names))

Accuracy Score:  0.8958157198847169
Confusion Matrix
 [[270983  21316]
 [ 17255  60665]]
Classification Report
               precision    recall  f1-score   support

     Class 0       0.94      0.93      0.93    292299
     Class 1       0.74      0.78      0.76     77920

    accuracy                           0.90    370219
   macro avg       0.84      0.85      0.85    370219
weighted avg       0.90      0.90      0.90    370219



### Decision Trees

In [12]:
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier()
dt.fit(X_train, y_train)

DecisionTreeClassifier()

In [13]:
dty_pred = dt.predict(X_test)

In [14]:
#Performance Metrics

from sklearn.metrics import accuracy_score, classification_report
from sklearn import metrics

print('Accuracy Score: ',accuracy_score(y_test, dty_pred))
cm = metrics.confusion_matrix(y_test, dty_pred)
print('Confusion Matrix\n',cm)
target_names=["Class 0","Class 1"]
print('Classification Report\n',classification_report(y_test, dty_pred,target_names=target_names))

Accuracy Score:  0.7917935060059046
Confusion Matrix
 [[230521  61778]
 [ 15304  62616]]
Classification Report
               precision    recall  f1-score   support

     Class 0       0.94      0.79      0.86    292299
     Class 1       0.50      0.80      0.62     77920

    accuracy                           0.79    370219
   macro avg       0.72      0.80      0.74    370219
weighted avg       0.85      0.79      0.81    370219



### Support Vector Machines

In [ ]:
from sklearn.svm import SVC
svc = SVC()
svc.fit(X_train,y_train)

In [ ]:
svcy_pred = svc.predict(X_test)

In [ ]:
#Performance Metrics

from sklearn.metrics import accuracy_score, classification_report
from sklearn import metrics

print('Accuracy Score: ',accuracy_score(y_test, etcy_pred))
cm = metrics.confusion_matrix(y_test, etcy_pred)
print('Confusion Matrix\n',cm)
target_names=["Class 0","Class 1"]
print('Classification Report\n',classification_report(y_test, etcy_pred,target_names=target_names))

### Extra Trees Classifier

In [15]:
from sklearn.ensemble import ExtraTreesClassifier
etc = ExtraTreesClassifier(n_jobs=-1,random_state = None)
etc.fit(X_train,y_train)

ExtraTreesClassifier(n_jobs=-1)

In [16]:
etcy_pred = etc.predict(X_test)

In [17]:
#Performance Metrics

from sklearn.metrics import accuracy_score, classification_report
from sklearn import metrics

print('Accuracy Score: ',accuracy_score(y_test, etcy_pred))
cm = metrics.confusion_matrix(y_test, etcy_pred)
print('Confusion Matrix\n',cm)
target_names=["Class 0","Class 1"]
print('Classification Report\n',classification_report(y_test, etcy_pred,target_names=target_names))

Accuracy Score:  0.889062960031765
Confusion Matrix
 [[265771  26528]
 [ 14543  63377]]
Classification Report
               precision    recall  f1-score   support

     Class 0       0.95      0.91      0.93    292299
     Class 1       0.70      0.81      0.76     77920

    accuracy                           0.89    370219
   macro avg       0.83      0.86      0.84    370219
weighted avg       0.90      0.89      0.89    370219



### XGBoost Classifier

In [18]:
import xgboost 
from xgboost import XGBClassifier
xgb = XGBClassifier()
xgb.fit(X_train, y_train)

D:\Softwares\Anaconda\lib\site-packages\dask\dataframe\utils.py:14: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
              importance_type='gain', interaction_constraints='',
              learning_rate=0.300000012, max_delta_step=0, max_depth=6,
              min_child_weight=1, missing=nan, monotone_constraints='()',
              n_estimators=100, n_jobs=0, num_parallel_tree=1, random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, subsample=1,
              tree_method='exact', validate_parameters=1, verbosity=None)

In [19]:
xgby_pred = xgb.predict(X_test)

In [20]:
#Performance Metrics

from sklearn.metrics import accuracy_score, classification_report
from sklearn import metrics

print('Accuracy Score: ',accuracy_score(y_test, xgby_pred))
cm = metrics.confusion_matrix(y_test, xgby_pred)
print('Confusion Matrix\n',cm)
target_names=["Class 0","Class 1"]
print('Classification Report\n',classification_report(y_test, xgby_pred,target_names=target_names))

Accuracy Score:  0.8957049746231285
Confusion Matrix
 [[269206  23093]
 [ 15519  62401]]
Classification Report
               precision    recall  f1-score   support

     Class 0       0.95      0.92      0.93    292299
     Class 1       0.73      0.80      0.76     77920

    accuracy                           0.90    370219
   macro avg       0.84      0.86      0.85    370219
weighted avg       0.90      0.90      0.90    370219

